# Generated by Django 5.0.2 on 2025-05-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='already_responded',
            field=models.BooleanField(default=False),
        ),
    ]
